/*
 * Copyright (c) 2014.  @石头哥哥
 * THIS SOFTWARE IS PROVIDED BY THE FREEBSD PROJECT ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoFile.proto

package proto;

public interface RoleVoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.RoleVo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required uint32 roleID = 1;</code>
   *
   * <pre>
   *角色ID
   * </pre>
   */
  boolean hasRoleID();
  /**
   * <code>required uint32 roleID = 1;</code>
   *
   * <pre>
   *角色ID
   * </pre>
   */
  int getRoleID();

  /**
   * <code>optional string roleName = 2;</code>
   *
   * <pre>
   *角色名称
   * </pre>
   */
  boolean hasRoleName();
  /**
   * <code>optional string roleName = 2;</code>
   *
   * <pre>
   *角色名称
   * </pre>
   */
  java.lang.String getRoleName();
  /**
   * <code>optional string roleName = 2;</code>
   *
   * <pre>
   *角色名称
   * </pre>
   */
  com.google.protobuf.ByteString
      getRoleNameBytes();

  /**
   * <code>optional uint32 roleSex = 3;</code>
   *
   * <pre>
   *角色性别
   * </pre>
   */
  boolean hasRoleSex();
  /**
   * <code>optional uint32 roleSex = 3;</code>
   *
   * <pre>
   *角色性别
   * </pre>
   */
  int getRoleSex();
}
